name: Executar programa Python

on:
    schedule:
      - cron: '*/5 * * * *'  

permissions:
    contents: write
    
jobs:
    execucio-temperaturea:
        runs-on: ubuntu-latest

        steps:
        - name: Clonar repositori
          uses: actions/checkout@v3

        - name: Configurar Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install-lar dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests

        - name: Executar programa
          run: python time.py

        - name: Fer commit del fitxer.json
          run: |
            git config user.name "alexnavarro"
            git config user.email "alex.navarro22@lacetania.cat"
            git add temp_*.json
            git commit -m "Fixer de temperatura diaria"	
            git push origin main
